/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.jhdf.kotlin.examples

import io.jhdf.HdfFile
import org.apache.commons.lang3.ArrayUtils

class App {}

fun main() {
    val file = App::class.java.getResource("test_file.hdf5")
    HdfFile(file.toURI()).use { hdfFile ->
        val dataset = hdfFile.getDatasetByPath("/datasets_group/float/float32")
        // data will be a java array of the dimensions of the HDF5 dataset
        val data = dataset.data
        System.out.println(ArrayUtils.toString(data))
    }
}
